/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/VintageRadio.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/VintageRadio.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.USB.geometry} material={materials.USB} position={[1.112, 0.425, -0.281]} rotation={[Math.PI, 0, Math.PI]} scale={30} />
      <mesh geometry={nodes.USBC.geometry} material={materials.USBC} position={[0.85, 0.415, -0.369]} rotation={[0, 1.571, 0]} scale={11.098} />
      <mesh geometry={nodes.Membrane.geometry} material={materials.Membrane} position={[-0.684, 0.63, 0.33]} rotation={[1.518, 0, 0]} scale={3.375}>
        <mesh geometry={nodes.Kork.geometry} material={materials.Kork} />
      </mesh>

      <mesh castShadow material-color={props.customColors.BodyHull} geometry={nodes.BodyHull.geometry} material={materials.BodyHull} position={[1.508, 1.271, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.MiddleRim} geometry={nodes.MiddleRim.geometry} material={materials.MiddleRim} position={[0.007, 1.118, 0.433]} rotation={[1.518, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.Grill} geometry={nodes.Grill.geometry} material={materials.Grill} position={[0.007, 0.575, 0.417]} rotation={[1.518, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.BackPanel} geometry={nodes.BackPanel.geometry} material={materials.BackPanel} position={[0.051, 0.601, 0.438]} rotation={[1.518, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.KnobRim} geometry={nodes.KnobRim.geometry} material={materials.KnobRim} position={[-1.133, 1.415, 0.407]} rotation={[1.518, 0, 0]} scale={0.152} />

      <mesh material-color={props.customColors.Knobs} geometry={nodes.Knobs.geometry} material={materials.Knobs} position={[-1.135, 1.422, 0.506]} rotation={[-1.623, 1.11, -Math.PI]} scale={0.139} />

      <mesh material-color={props.customColors.RodHandle} geometry={nodes.RodHandle.geometry} material={materials.RodHandle} position={[0.007, 2.04, -0.048]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.025} />

      <mesh material-color={props.customColors.RubberHandle} geometry={nodes.RubberHandle.geometry} material={materials.RubberHandle} position={[0.007, 2.318, -0.048]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.025} />

      <mesh material-color={props.customColors.HandlePadding} geometry={nodes.HandlePadding.geometry} material={materials.HandlePadding} position={[1.599, 1.22, -0.044]} rotation={[0, 0, -1.49]} />

      <mesh material-color={props.customColors.Band} geometry={nodes.Band.geometry} material={materials.Band} position={[1.508, 1.271, -0.023]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.KnobMarker} geometry={nodes.KnobMarker.geometry} material={materials.KnobMarker} position={[-1.134, 1.419, 0.505]} rotation={[-1.623, 1.11, -Math.PI]} scale={0.139} />

      <mesh material-color={props.customColors.Screen} geometry={nodes.Screen.geometry} material={materials.Screen} position={[0.007, 1.571, 0.392]} rotation={[1.518, 0, -Math.PI / 2]} />

      <mesh material-color={props.customColors.DisplayText} geometry={nodes.DisplayText.geometry} material={materials.DisplayText} position={[0.007, 1.571, 0.392]} rotation={[1.518, 0, -Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/VintageRadio.glb')
